name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test-build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux
          - os: macos-latest
            name: Darwin
          - os: windows-latest
            name: Windows
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18.4"

      - name: setting up java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Run build tests
        run: |
          set -x;
          go install github.com/rajveermalviya/tsukuru/cmd/tsukuru;

          tsukuru build apk github.com/rajveermalviya/tsukuru/examples/android-deps;
          tsukuru build apk github.com/rajveermalviya/tsukuru/examples/android-nodeps;
          tsukuru -androidbackend=custom build apk github.com/rajveermalviya/tsukuru/examples/android-nodeps;

          tsukuru build appbundle github.com/rajveermalviya/tsukuru/examples/android-deps;
          tsukuru build appbundle github.com/rajveermalviya/tsukuru/examples/android-nodeps;

          tsukuru -release build apk github.com/rajveermalviya/tsukuru/examples/android-deps;
          tsukuru -release build apk github.com/rajveermalviya/tsukuru/examples/android-nodeps;
          tsukuru -release -androidbackend=custom build apk github.com/rajveermalviya/tsukuru/examples/android-nodeps;

          tsukuru -release build appbundle github.com/rajveermalviya/tsukuru/examples/android-deps;
          tsukuru -release build appbundle github.com/rajveermalviya/tsukuru/examples/android-nodeps;

        shell: bash
